applications:
  - id: "myagent"
    name: "My First Coral Agent"
    description: "An example AI agent that echoes back messages"
    secret: "mysecret"  # used for agent authentication
    mcpEndpoint: "http://127.0.0.1:6001/agent"